### ISSUE TITLE
CurveTo(float xLoc, float yLoc)

### ISSUE THREAD

**Issue by philipp-lehmann** [evil-mad/AxiDraw-Processing#1]
Hi there

How would you implement beziercurves?
As far as I understand it, there is currently only `MoveToXY(int xLoc, int yLoc)` and this moves in a straight line.

My best guess is that you have calculate and add the curve to `ani.to`?
Any other ideas?

Best Philipp

**Comment by oskay** [comment]
There is not a function like "CurveTo" in this repository.

To manage following curves, either flatten the curve into straight segments or export SVG and plot with the main AxiDraw software.

**Comment by philipp-lehmann** [comment]
Thanks for your answer.

Yes, I know curves can be drawn when exporting SVGs. I did that a lot.
But now I'd like to draw curves directly from processing. (Ideally combining it with the zPos/brushHeight.)

I first tried emulating it with `MoveToXY()` but since this uses integers, the resolution is just not enough. The drawing get jiggly.

Any other ideas?

**Comment by oskay** [comment]
The AxiDraw uses stepper motors, and _is_ limited to movements that take place in integer units.

I don't know which program you're running from this repository, which settings you are using while doing so, or what kind of a machine you are trying to control with this, but if it's an AxiDraw, then the resolution -- while yes limited by integers -- is much, much finer than the width of any physical pen that we are aware of.

We generally do not consider the fact that integers are used as a limit. Can you say a bit about what you are doing that makes this a limit?

**Comment by philipp-lehmann** [comment]
I try to imitate brush strokes. 
Hence i'd like to move the brush in a curve or a circle meanwhile lifting it slowly. 

At the moment a calculate quite a lot of points to move smoothly. However the lines around a 45° angle, get rendered as a zigzag line. I guess because the coordinates are rounded to integers.

You can see how the problem shows in the attached img. 
![img](https://user-images.githubusercontent.com/4519837/93806049-ddf6b800-fc48-11ea-9809-b981bfa7ee5b.png)

So instead I'd like to increase the distance between each command but draw a curve instead.
Best Philipp

**Comment by oskay** [comment]
Rounding to integer steps should give you a minimum resolution of roughly 113 steps/mm (2874 steps/inch). Since I can see those steps in a picture big enough to see the pen, it seems like something is being rounded at a higher level.

**Comment by philipp-lehmann** [comment]
I think the problem is the sketch size in processing which is much smaller than the possible resolution.
Somewhere theres probably a multiplicator (`native units`)?

Thanks for this input.

**Comment by philipp-lehmann** [comment]
I found `MotorStepsPerPixel`. Thats probably where I need to continue.

**Comment by oskay** [comment]
Again, I don't know which program you're using, or what exactly you're trying to do. MotorStepsPerPixel, in both programs here, controls the ratio between the pixels in the window versus what the machine does. Without scaling down, you'll need a larger than typical screen to display motor steps at 1:1 on the screen.
