### ISSUE TITLE
zPos

### ISSUE THREAD

**Issue by philipp-lehmann** [evil-mad/AxiDraw-Processing#2]
Hi again

I would also like to control the height of the pen. There are `lowerBrush()` and `raiseBrush()` functions, but how would approach it, if you want to change the height while drawing?

Thanks for any ideas.
Cheers Philipp

**Comment by oskay** [comment]
I would suggest changing the `delayAfterRaisingBrush` and `delayAfterLoweringBrush` commands to zero. Then there will not be a delay after starting to raise or lower the pen -- you can keep feeding XY movement commands.
