### ISSUE TITLE
Failure to connect (?) windows

### ISSUE THREAD

**Issue by PauRosello97** [evil-mad/AxiDraw-Processing#3]
Hi, are there any news to use AxiDraw with Processing in Windows?

Any workaround?

**Comment by oskay** [comment]
Seriously?

**Comment by PauRosello97** [comment]
I guess it's a stupid question but I don't know why. Sorry for that.

**Comment by oskay** [comment]
You're saying that it has never worked with Windows and asking for an update and a workaround for the "fact" that it doesn't.

If *you* are having trouble using it on Windows, that would be worthy of an issue report. But that issue report would need to start with what your exact configuration is, what type of problem you are encountering, including specifics of what type of error message or other type of "not working" is going on.  Just claiming that it never worked and asking for an update is _really_ not a good way to ask for help.

**Comment by PauRosello97** [comment]
Ohh sorry for that. I missunderstood this comment in the readme.txt:

![image](https://user-images.githubusercontent.com/49373982/152897381-91449954-1b84-4089-8e52-d4c91f57796a.png)

I thought that ment that it did not work for Windows, but I guess there are certain cases where it works. Sorry for that. Let me start again.

Hi, I tried to use both of the examples in Windows, but it's not working. I debugged the code, and I found that the problem is in the line `myPort.write("v\r");` in the file utils.pde.

I've then seen that in the readme.txt it says that this is a know issue, so I wonder if there's a workaround for Windows users or other new examples. 

Thank you.

**Comment by oskay** [comment]
Yeah, I got around to it about 8 years ago, but forgot to update the readme when copying it from an older project. (It doesn't load files either.)

> Hi, I tried to use both of the examples in Windows, but it's not working.

Can you please clarify exactly *what* behavior you are seeing? For example, does it list any serial ports when it runs? Can you copy and paste the output of the text that is printing when it runs?

**Comment by PauRosello97** [comment]
Thanks Windell,

Here's what I see in the console: 

> Ani 2.7 infos, feedback ...
> I found 3 serial ports, which are:
> COM3 COM4 COM6
> Serial port COM3 could not be activated.
> Serial port COM4 found and activated.

The screen remains blank. I've debugged the code, and it gets stuck here: `myPort.write("v\r");` in the utils.pde. 

I don't know if it's useful or not, but the Inkscape Extension and the Python API works fine. 

Thank you.

**Comment by oskay** [comment]
It sounds like you may have either (1) the AxiDraw already connected to another port or software interface, or (2) another device that it's mistakenly identifying as an AxiDraw and trying to communicate with.

Do you know if your AxiDraw is on COM3, 4, or 6? You can check with the Read tab of the AxiDraw Naming utility in Inkscape.

**Comment by PauRosello97** [comment]
I checked in Inkscape, and it's COM6, then I guess that it's trying to connect with another device in COM4. I don't have more connected devices, so I guess there's a problem in my computer. I'll check what's happening.

Thanks Windell, for your work and your help, and sorry for the confusion and my bad formulated question.

Thank you

**Comment by oskay** [comment]
I'd suggest restarting the computer as a first step. Also, possibly, check with your device manager or the `mode` command in a command prompt to see what else is on there.

**Comment by PauRosello97** [comment]
Hi Windell
It was detecting a bluetooth device and trying to connect to it. I just disabled Bluetooth, and works fine now.

We can close this issue.

Once again, thanks for your work and help.

**Comment by oskay** [comment]
Interesting -- thank you for the update!
